### ISSUE TITLE
Viewing of comments/annotations in mobile devices

### ISSUE THREAD

**Issue by Natkeeran** [contently/videojs-annotation-comments#43]
We are evaluating this plugin to see if this can be used to create video annotations.   

We noted that this plugin is tested against various [desktop browsers](https://github.com/contently/videojs-annotation-comments/issues/10).  We did some initial responsive/mobile devices testing, mainly looking to see if the annotations/comments can be viewed in mobile devices. 

* iOS - Able to view annotations, however, it does not load the annotations UI elements in full screen mode.
* Andorid - The button appears.  However, none of the UI elements are shown (not able to view).

Is there any plan to support viewing of annotations in mobile/responsive devices?

**Comment by jackpope** [comment]
Hi @Natkeeran, thanks for checking out the plugin!

There are no plans currently to support more mobile devices. PRs are always welcome though 😃 

As for iOS, my expectation is that in full screen, the system player would be used rather than the videojs player. I am not sure if there would be a way around this. Any ideas?

Android do you know if there are any specific errors that prevent the plugin from loading?

**Comment by Natkeeran** [comment]
@jackpope 
@jackpope 

Thank you for the reply.  

I see your note about the system player taking over in iOS.  No suggestions at this moment.

The Andorid behavior is similar to Chrom's Responsive mode behaviour.  No js errors are thrown though.

**Comment by jackpope** [comment]
Closing this for now due to inactivity and no plans to work around mobile native players
