### ISSUE TITLE
Add more shapes and free drawing

### ISSUE THREAD

**Issue by NourBAmmar** [contently/videojs-annotation-comments#64]
Hello, i want to annotate videos with more shapes and free drawing not only rectangles. Is it possible using this plugin ?

**Comment by jamesconant** [comment]
I _believe_ that right now it only supports rectangles. 

@jackpope any thoughts on this one?

If it does not currently support that you are more than welcome to make any contributions or proposals to help implement that feature.

**Comment by jackpope** [comment]
Yeah that's right. Only rectangles out of the box.

If you wanted to support custom shapes you could try forking this plugin and updating the Shape and SelectableShape components to be based on a collection of x/y values instead of the current coordinate structure (x1,y1,x2,y2), which defines the corners of a rectangle. Your SelectableShape could insert points into the collection and render lines between them via svg as you draw. Then Shape can continue to be a static rendering of what you've drawn.

I'm not sure how coupled the rectangle structure is with the rest of the library as it's been a while since working on shapes.

https://github.com/contently/videojs-annotation-comments/blob/master/src/js/components/selectable_shape.js

https://github.com/contently/videojs-annotation-comments/blob/master/src/js/components/shape.js

**Comment by jackpope** [comment]
@ecaroth I know you still dream about this feature 😄

**Comment by NourBAmmar** [comment]
Ok thanks for your help i will try to do this
